spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 172.20.10.10
    port: 6379
    #password:
server:
  context-path: /
#  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug
wechat:
  # 微信授权 id
#  mpAppId: wx0465fe3767346d03
#  mpAppSecret: 98f3f91786611085871483c1b799aaf5
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
  openAppId: xxxxxxxxxxxxxxxxxx
  openAppSecret: xxxxxxxxxxxxxxxxxxxxx
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath:  C:/Users/Hasee/Desktop/SpringBoot_Wechat_Sell/src/main/resources/h5.p12
  notifyUrl: http://xiazhong.natapp1.cc/notify
  templateId:
    orderStatus: kahmCfZjV-2jORZ4yFti9-69smaV3gQ1lFFCDKL_vjI
    payStatus: kahmCfZjV-2jORZ4yFti9-69smaV3gQ1lFFCDKL_vjI

projectUrl:
  wechatMpAuthorize: http://xiazhong.natapp1.cc
  wechatOpenAuthorize: http://xiazhong.natapp1.cc
  sell: http://localhost:8080
logging:
  level:
    com.ldlood.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml





